"""
Backward-compatibility package — prefer ``palm.common`` for new code.

Re-exports the shared coordination API formerly rooted here.
"""

from palm.common import (
    DefinitionBuildError,
    DefinitionExecutor,
    DefinitionNotFoundError,
    DefinitionRepository,
    ExecutionError,
    ExecutionPlan,
    FlowSubmission,
    InstanceNotFoundError,
    InstancePersistenceHook,
    InstanceRepository,
    InstanceResumeError,
    PatternBuildContext,
    PlanNotFoundError,
    PlanRegistry,
    PlanValidationError,
    ProcessInstance,
    ProcessPlan,
    StatusHistoryEntry,
    StoredPlan,
    build_pattern,
    parse_wizard_flow_options,
    prepare_flow_submission,
    prepare_process_plans,
    wizard_config_from_options,
    wizard_metadata_from_flow,
)

__all__ = [
    "DefinitionBuildError",
    "DefinitionExecutor",
    "DefinitionNotFoundError",
    "DefinitionRepository",
    "ExecutionError",
    "ExecutionPlan",
    "FlowSubmission",
    "InstanceNotFoundError",
    "InstancePersistenceHook",
    "InstanceRepository",
    "InstanceResumeError",
    "PatternBuildContext",
    "PlanNotFoundError",
    "PlanRegistry",
    "PlanValidationError",
    "ProcessInstance",
    "ProcessPlan",
    "StatusHistoryEntry",
    "StoredPlan",
    "build_pattern",
    "parse_wizard_flow_options",
    "prepare_flow_submission",
    "prepare_process_plans",
    "wizard_config_from_options",
    "wizard_metadata_from_flow",
]